### ISSUE TITLE
PWM object exists for GPIO channel

### ISSUE THREAD

**Issue by wtgee** [pimoroni/explorer-hat#43]
Just got my explorerhat and running it through some tests. Seems like I get

```python
RuntimeErro: A PWM object already exists for this GPIO channel
```
after just about everything I do. I don't see anything in the docs to indicate there is some proper usage that I'm not properly using.

On python3.6.6 in a jupyter-console (5.2.0) (via berryconda) with a forked version of the repo.

I can successfully toggle things occasionally and even read some analog inputs, but it seems like I have to kill the console after every successful usage. Any tips apprecaited. Thanks!

**Comment by Gadgetoid** [comment]
I'm guessing the way jupyter-console works - presumably not starting with a clean session on every execution - is fundamentally incompatible with the `RPi.GPIO` library. Unfortunately I'm not sure there's much I can do about this. Perhaps trapping and ignoring the `RuntimeError` would work, although that would be a very usage-specific and weird addition to the library itself.

Closing this issue for now because it's ancient, but if you're still having trouble I'll have to admit I'm at a loss (since I don't have any experience with these environments) and I'm open to suggestions.
